Controllers films users
Nikitarsis/java-filmorate pull request #8
Opened 2023-03-22 19:43 UTC by Nikitarsis

2023-03-23 20:37 UTC, mikita95 requested changes
Все работает верно :) Нужно только поправить пару моментов.

2023-03-23 20:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/containers/StandardContainer.java
> +//@Component
Закомментированный код - лучше не оставлять такого :)

2023-03-23 20:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @Autowired
Лучше не использовать `@Autowired` над полями (не в тестах, по крайней мере), а использовать его над конструктором, поле же можно сделать final - так удобнее тестировать код, и spring точно заинжектит объект

2023-03-23 20:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public boolean isValid() {
Лучше было бы вынести логику валидации в отдельный класс (можно сделать спринговым бином) - класс модели данных предпочтительнее оставлять простым, а валидация может быть разной. 

Из разряда можно лучше:
можно улучшить валидацию, добавив зависимость 
```<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-validation</artifactId>
</dependency>
```

и использовать аннотации  `@NotNull` к полям класса-модели для проверки на `null`, `@NotBlank` — для проверки на пустую строку, `@Email` — для проверки на соответствие формату электронного адреса. и другие

2023-03-23 20:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    final Long id;
Поля лучше сделать private - так надежнее :)
Отмечу также, что в lombok, есть аннотация `@Value`, которая позволяет сделать класс немутабельным.
Но есть объект сериализуется и десериализуется в json, то лучше поля сделать не final, а также добавить конструктор по-умолчанию. Иногда, если не заметить и поменять версию библиотеки сериализации json или изменить ее конфигурацию, то она не сможет десериализовать объект. Но сейчас все ок, раз тесты проходят :)

2023-03-23 20:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +public class UserService implements StandartService<User>{
Не хватает пробела :)

2023-03-23 20:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    StandardContainer<User> users = new StandardContainer<>();
Не хватает private (final)

2023-03-24 13:32 UTC, Nikitarsis commented on src/main/java/ru/yandex/practicum/filmorate/containers/StandardContainer.java
> +//@Component
Кстати, вот это я специально оставил это, чтобы спросить, как сделать так, чтобы спринг создавал два объекта этого класса, а не один, из-за чего у меня валилась вся программа при попытке привести Film к User или наоборот? Это делается только через @Configuration?

2023-03-25 08:56 UTC, mikita95 requested changes
Все работает верно :) Нужно поправить пару моментов еще.

2023-03-25 08:56 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    protected final StandartService<FilmValidationContainer> service;
Где-то использовано standar**t**, а где-то standar**d**

2023-03-25 08:56 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/containers/StandardContainer.java
> +public class StandardContainer<T extends StandardModel> {
Лучше сделать этот класс абстрактным, а его две реализации сделать как раз бинами, иначе в данном случае, у вас один контейнер на все

2023-03-25 08:56 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
Лишний перенос строк

2023-03-25 08:56 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/containers/FilmValidationContainer.java
> +public class FilmValidationContainer implements ValidationContainer {
Можно лучше: лучше было бы сделать просто отдельный сервис для валидации, а целом, валидация нужно только в одном месте, и таскать эту обертку везде не очень удобно

2023-03-25 08:56 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    public FilmService(StandardContainer<FilmValidationContainer> container) {}
Этот конструктор тогда не нужен, вы просто инициализировали вручную поле. Либо поправить структуру бинов и использовать бин

2023-03-25 09:18 UTC, Nikitarsis commented on src/main/java/ru/yandex/practicum/filmorate/containers/StandardContainer.java
> +public class StandardContainer<T extends StandardModel> {
Спасибо. Добавил классы-наследники, теперь всё работает нормально.

2023-03-25 09:18 UTC, Nikitarsis commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    protected final StandartService<FilmValidationContainer> service;
Я посередине работы внезапно узнал, что правильнее standar**d**

2023-03-25 10:05 UTC, Nikitarsis commented on src/main/java/ru/yandex/practicum/filmorate/model/containers/FilmValidationContainer.java
> +public class FilmValidationContainer implements ValidationContainer {
Я всё же считаю, что контейнеры с функцией валидации вполне проходят для задачи. Тем не менее, я сделал все функции валидации статическими, чтобы в случае расширения функционала контейнера или необходимости использовать различные внутренние конфигурации валидатора, последовать вашему совету и выделить отдельный класс для валидации не составило бы труда.

2023-03-25 10:34 UTC, mikita95 approved these changes
Все верно :) Можно мержить пул-реквест

2023-03-25 10:36 UTC, merged